### PR TITLE
Global upgrade of the plugin

### PR DESCRIPTION
**Pull request by utarwyn**
This PR upgrades some files and dependencies based on what are done in other Drone plugins.

- Bump Go from 1.19 to 1.21
- Upgrade dependencies
- Update gitignore
- Remove custom golangci-lint configuration

Should be integrated before #155 in order to fix the build.

### CODE REVIEW

**Comment by donny-dont** [comment]
Why is the `.golangci.yml` deleted? Also why Go 1.20 instead of Go 1.21?

**Comment by utarwyn** [comment]
> @donny-dont 
> Why is the `.golangci.yml` deleted? Also why Go 1.20 instead of Go 1.21?

This file seems to be deleted in other maintained plugins, no? Without the file, golangci-lint works with the default configuration and linters ([see more here](https://golangci-lint.run/usage/linters/#enabled-by-default)). Let me know if you still want to keep it (but we will need to update it).

Yes I can upgrade to Go 1.21 directly if you want

**Comment by utarwyn** [comment]
Hello @donny-dont @tphoney,
I have updated the plugin to Go 1.21. Can you review the PR?

**Review by tphoney — APPROVED** [review]

**Comment by tphoney** [comment]
thanks for the PR @utarwyn merged.

**Comment by utarwyn** [comment]
Thank you for the quick review! 🚀

**Pull request merged**
